name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.9.1+1
homepage: https://github.com/cachapa/firedart

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  http: ^0.13.5
  grpc: ^3.1.0
  protobuf: ^2.1.0
  fixnum: ^1.1.0

dev_dependencies:
  lints: any
  test: any
